const verbsReview4 = [
  {entry: "agō",
  infinitive: "agere",
  thirdPart: "ēgī",
  supine: "āctum",
  meanings: "do, drive"},
  {entry: "aperiō",
    infinitive: "aperīre",
    thirdPart: "aperuī",
    supine: "apertum",
    meanings: "open"},
  {entry: "audiō",
    infinitive: "audīre",
    thirdPart: "audīvī",
    supine: "audītum",
    meanings: "hear listen to"},
  {entry: "bibō",
    infinitive: "bibere",
    thirdPart: "bibī",
    supine: "bibitum",
    meanings: "drink"},
  {entry: "capiō",
    infinitive: "capere",
    thirdPart: "cēpī",
    supine: "captum",
    meanings: "take"},
  {entry: "cedō",
    infinitive: "cēdere",
    thirdPart: "cessī",
    supine: "cessum",
    meanings: "yield; go (in a certain direction)"},
  {entry: "claudō",
    infinitive: "claudere",
    thirdPart: "clausī",
    supine: "clausum",
    meanings: "close, shut"},
  {entry: "cōgō",
    infinitive: "cōgere",
    thirdPart: "coēgī",
    supine: "coāctum",
    meanings: "gather, assemble, drive; force"},
  {entry: "crēscō",
    infinitive: "crēscere",
    thirdPart: "crēvī",
    supine: "crētum",
    meanings: "grow"},
  {entry: "cupiō",
    infinitive: "cupere",
    thirdPart: "cupīvī",
    supine: "cupītum",
    meanings: "want, desire"},
  {entry: "currō",
    infinitive: "currere",
    thirdPart: "cucurrī",
    supine: "cursum",
    meanings: "run"},
  {entry: "custōdiō",
    infinitive: "custōdīre",
    thirdPart: "custōdīvī",
    supine: "custōdītum",
    meanings: "protect, guard, take care of"},
  {entry: "dīcō",
    infinitive: "dicere",
    thirdPart: "dīxī",
    supine: "dīctum",
    meanings: "say, tell"},
  {entry: "discō",
    infinitive: "discere",
    thirdPart: "didicī",
    supine: "discitum",
    meanings: "learn"},
  {entry: "dormiō",
    infinitive: "dormīre",
    thirdPart: "dormīvī",
    supine: "dormītum",
    meanings: "sleep"},
  {entry: "dūcō",
    infinitive: "dūcere",
    thirdPart: "dūxī",
    supine: "ductum",
    meanings: "lead, bring"},
  {entry: "edō",
    infinitive: "edere",
    thirdPart: "ēdī",
    supine: "ēsum",
    meanings: "eat"},
  {entry: "ēsuriō",
    infinitive: "ēsurīre",
    thirdPart: "ēsurīvī",
    supine: "ēsurītum",
    meanings: "be hungry"},
  {entry: "faciō",
    infinitive: "facere",
    thirdPart: "fēcī",
    supine: "factum",
    meanings: "make, do"},
  {entry: "fallō",
    infinitive: "fallere",
    thirdPart: "fefellī",
    supine: "falsum",
    meanings: "deceive, be wrong"},
  {entry: "ferō",
    infinitive: "ferre",
    thirdPart: "tulī",
    supine: "lātum",
    meanings: "carry, bear, bring"},
  {entry: "fīniō",
    infinitive: "fīnīre",
    thirdPart: "fīnīvī",
    supine: "fīnītum",
    meanings: "end, finish; bound"},
  {entry: "frangō",
    infinitive: "frangere",
    thirdPart: "frēgī",
    supine: "frāctum",
    meanings: "break"},
  {entry: "fugiō",
    infinitive: "fugere",
    thirdPart: "fūgī",
    supine: "fūgitum",
    meanings: "flee, fly, run away"},
  {entry: "gerō",
    infinitive: "gerere",
    thirdPart: "gessī",
    supine: "gestum",
    meanings: "bear, carry out, wear"},
  {entry: "iaciō",
    infinitive: "iacere",
    thirdPart: "iēcī",
    supine: "iāctum",
    meanings: "throw, toss, cast"},
  {entry: "igniō",
    infinitive: "ignīre",
    thirdPart: "ignīvī",
    supine: "ingītum",
    meanings: "set afire"},
  {entry: "iungō",
    infinitive: "iungere",
    thirdPart: "iūnxī",
    supine: "iunctum",
    meanings: "join, yoke"},
  {entry: "legō",
    infinitive: "legere",
    thirdPart: "lēgī",
    supine: "lēctum",
    meanings: "gather, collect; read"},
  {entry: "lūdō",
    infinitive: "lūdere",
    thirdPart: "lūsī",
    supine: "lūsum",
    meanings: "play"},
  {entry: "mittō",
    infinitive: "mittere",
    thirdPart: "mīsī",
    supine: "missum",
    meanings: "send"},
  {entry: "mūniō",
    infinitive: "mūnīre",
    thirdPart: "mūnīvī",
    supine: "mūnītum",
    meanings: "fortify, build up"},
  {entry: "nesciō",
    infinitive: "nescīre",
    thirdPart: "nescīvī",
    supine: "nescītum",
    meanings: "not know, be unaware of"},
  {entry: "ningit",
    infinitive: "ningere",
    thirdPart: "ninxit",
    supine: "---",
    meanings: "it snows"},
  {entry: "nōscō",
    infinitive: "nōscere",
    thirdPart: "nōvī",
    supine: "nōtum",
    meanings: "recognize, be familiar with"},
  {entry: "ostendō",
    infinitive: "ostendere",
    thirdPart: "ostendī",
    supine: "ostentum",
    meanings: "show, show off"},
  {entry: "pellō",
    infinitive: "pellere",
    thirdPart: "pepulī",
    supine: "pulsum",
    meanings: "drive, push"},
  {entry: "petō",
    infinitive: "petere",
    thirdPart: "petīvī",
    supine: "petītum",
    meanings: "seek, ask of"},
  {entry: "pluit",
    infinitive: "pluere",
    thirdPart: "plūvīt",
    supine: "---",
    meanings: "it rains"},
  {entry: "pōnō",
    infinitive: "pōnere",
    thirdPart: "posuī",
    supine: "positum",
    meanings: "put, place"},
  {entry: "puniō",
    infinitive: "punīre",
    thirdPart: "punīvī",
    supine: "punītum",
    meanings: "punish"},
  {entry: "quaeō",
    infinitive: "quaerere",
    thirdPart: "quaesīvī",
    supine: "quaestum",
    meanings: "inquire, seek out"},
  {entry: "rapiō",
    infinitive: "rapere",
    thirdPart: "rapuī",
    supine: "raptum",
    meanings: "seize, grab"},
  {entry: "regō",
    infinitive: "regere",
    thirdPart: "rēxī",
    supine: "rēctum",
    meanings: "rule; guide"},
  {entry: "sapiō",
    infinitive: "sapere",
    thirdPart: "sapuī",
    supine: "---",
    meanings: "have flavor; be wise, be aware, know how"},
  {entry: "sciō",
    infinitive: "scīre",
    thirdPart: "scīvī",
    supine: "scītum",
    meanings: "know (a fact)"},
  {entry: "scrībō",
    infinitive: "scrībere",
    thirdPart: "scrīpsī",
    supine: "scrīptum",
    meanings: "write"},
  {entry: "sentiō",
    infinitive: "sentīre",
    thirdPart: "sēnsī",
    supine: "sēnsum",
    meanings: "feel, perceive"},
  {entry: "serviō",
    infinitive: "servīre",
    thirdPart: "servīvī",
    supine: "servītum",
    meanings: "serve, be a servant to (+Dat.)"},
  {entry: "statuō",
    infinitive: "statuere",
    thirdPart: "statuī",
    supine: "statutum",
    meanings: "set up, determine"},
  {entry: "struō",
    infinitive: "struere",
    thirdPart: "strūxī",
    supine: "strūctum",
    meanings: "build"},
  {entry: "tangō",
    infinitive: "tangere",
    thirdPart: "tetigī",
    supine: "tāctum",
    meanings: "touch"},
  {entry: "trādō",
    infinitive: "trādere",
    thirdPart: "trādidī",
    supine: "trāditum",
    meanings: "hand over, surrender"},
  {entry: "trahō",
    infinitive: "trahere",
    thirdPart: "trāxī",
    supine: "trāctum",
    meanings: "pull, drag"},
  {entry: "vehō",
    infinitive: "vehere",
    thirdPart: "vexī",
    supine: "vectum",
    meanings: "convey, transport"},
  {entry: "veniō",
    infinitive: "venīre",
    thirdPart: "vēnī",
    supine: "ventum",
    meanings: "come"},
  {entry: "vertō",
    infinitive: "vertere",
    thirdPart: "vertī",
    supine: "versum",
    meanings: "turn"},
  {entry: "vincō",
    infinitive: "vincere",
    thirdPart: "vīcī",
    supine: "victum",
    meanings: "conquer, defeat"},
  {entry: "vīvō",
    infinitive: "vīvere",
    thirdPart: "vīxī",
    supine: "vīctum",
    meanings: "live, be alive"},
  {entry: "volvō",
    infinitive: "volvere",
    thirdPart: "volvī",
    supine: "volūtum",
    meanings: "spin, roll"}
]

let verbsLength = verbsReview4.length;

function displayVerbs() {
  let j = 1;
  let html = `<ol style="1" start="${j}">`;
  let iteration = "";

  for (let i = 0; i < verbsLength; i++) {
    iteration += `<div id="verb-item-${j}" class="container-flex"><li id="li-${j}">`;
    iteration += `<div id="top-row-${j}" class="row">`
    iteration += `<span id="latin-span-${j}" style="width: 100%; margin-left: 20px"><strong>${verbsReview4[i].entry}, `;
    iteration += `${verbsReview4[i].infinitive}, `;
    iteration += `${verbsReview4[i].thirdPart}, `;
    iteration += `${verbsReview4[i].supine}</strong>`;
    iteration += ` — <em>${verbsReview4[i].meanings}</em></span>`;
    iteration += `</div></li><hr/>`;
    }
    j++;

  html += iteration;
  html += "</ol>";
  return html;
}
