const nounsReview4 = [
  {entry: "aestās",
    genitive: "aestātis",
    gender: "f.",
    meanings: "summer"},
  {entry: "aetās",
    genitive: "aetātis",
    gender: "f.",
    meanings: "age, era"},
  {entry: "agmen",
    genitive: "agminis",
    gender: "n.",
    meanings: "marching column"},
  {entry: "actiō",
    genitive: "actiōnis",
    gender: "f.",
    meanings: "action, the act of doing"},
  {entry: "annus",
    genitive: "annī",
    gender: "m.",
    meanings: "year"},
  {entry: "apertūra",
    genitive: "apertūrae",
    gender: "f.",
    meanings: "opening"},
  {entry: "auditiō",
    genitive: "auditiōnis",
    gender: "f.",
    meanings: "audition, the act of hearing or listening"},
  {entry: "cessiō",
    genitive: "cessiōnis",
    gender: "f.",
    meanings: "surrender, the act of yielding"},
  {entry: "clausūra",
    genitive: "clausūrae",
    gender: "f.",
    meanings: "closure"},
  {entry: "-clūsiō",
    genitive: "-clūsiōnis",
    gender: "f.",
    meanings: "the act of closing or shutting"},
  {entry: "clēmentia",
    genitive: "clēmentiae",
    gender: "f.",
    meanings: "mercy"},
  {entry: "commūnitās",
    genitive: "commūnitātis",
    gender: "f.",
    meanings: "community, commonwealth"},
  {entry: "cōnsilium",
    genitive: "cōnsiliī",
    gender: "n.",
    meanings: "council, advice, plan"},
  {entry: "crīmen",
    genitive: "crīminis",
    gender: "n.",
    meanings: "crime, infraction"},
  {entry: "crūdēlitās",
    genitive: "crūdēlitātis",
    gender: "f.",
    meanings: "cruelty"},
  {entry: "custōs",
    genitive: "custōdis",
    gender: "u.",
    meanings: "guardian, protector"},
  {entry: "decus",
    genitive: "decoris",
    gender: "n.",
    meanings: "honor, distinction"},
  {entry: "dēmentia",
    genitive: "dēmentiae",
    gender: "f.",
    meanings: "lack of mental faculties"},
  {entry: "dictiō",
    genitive: "dictiōnis",
    gender: "f.",
    meanings: "speech, the act of speaking"},
  {entry: "diēs",
    genitive: "diēī",
    gender: "m.",
    meanings: "day"},
  {entry: "dormītōrium",
    genitive: "dormītōriī",
    gender: "n.",
    meanings: "sleeping quarters"},
  {entry: "dūritia",
    genitive: "dūritiae",
    gender: "f.",
    meanings: "hardness, rigidity"},
  {entry: "factiō/-fectiō",
    genitive: "factiōnis/-fectiōnis",
    gender: "f.",
    meanings: "faction; the act of doing or making"},
  {entry: "frāctiō",
    genitive: "fractiōnis",
    gender: "f.",
    meanings: "fraction, portion; the act of breaking"},
  {entry: "fractūra",
    genitive: "fractūrae",
    gender: "f.",
    meanings: "breakage"},
  {entry: "fūga",
    genitive: "fūgae",
    gender: "f.",
    meanings: "flight"},
  {entry: "grāmen",
    genitive: "grāminis",
    gender: "n.",
    meanings: "grass, herb"},
  {entry: "hiems",
    genitive: "hiemis",
    gender: "f.",
    meanings: "winter"},
  {entry: "hōra",
    genitive: "hōrae",
    gender: "f.",
    meanings: "hour"},
  {entry: "hōrologium",
    genitive: "hōrologiī",
    gender: "n.",
    meanings: "clock"},
  {entry: "hostīlitās",
    genitive: "hostīlitātis",
    gender: "f.",
    meanings: "hostility, enmity"},
  {entry: "īdūs",
    genitive: "īduum",
    gender: "f.",
    meanings: "Ides, 13<sup>th</sup> or 15<sup>th</sup> of the month"},
  {entry: "-iectiō",
    genitive: "-iectiōnis",
    gender: "f.",
    meanings: "the act of throwing or casting"},
  {entry: "iecur",
    genitive: "iecoris",
    gender: "n.",
    meanings: "liver"},
  {entry: "ingentia",
    genitive: "ingentiae",
    gender: "f.",
    meanings: "hugeness, enormity"},
  {entry: "iūnctiō",
    genitive: "iūnctiōnis",
    gender: "f.",
    meanings: "junction, joint, the act of joining"},
  {entry: "iūs",
    genitive: "iūris",
    gender: "n.",
    meanings: "legal right, law"},
  {entry: "iūstitia",
    genitive: "iūstitiae",
    gender: "f.",
    meanings: "justice, rightness"},
  {entry: "kalendae",
    genitive: "kalendārum",
    gender: "f.",
    meanings: "Kalends, first day of a month"},
  {entry: "kalendārium",
    genitive: "kalendāriī",
    gender: "n.",
    meanings: "calendar"},
  {entry: "-lātiō",
    genitive: "-lātiōnis",
    gender: "f.",
    meanings: "the act of brining or bearing"},
  {entry: "lectiō",
    genitive: "lectiōnis",
    gender: "f.",
    meanings: "lesson, the act of reading"},
  {entry: "līmen",
    genitive: "līminis",
    gender: "n.",
    meanings: "threshold, lintel"},
  {entry: "lītus",
    genitive: "lītoris",
    gender: "n.",
    meanings: "shore"},
  {entry: "mel",
    genitive: "mellis",
    gender: "n.",
    meanings: "honey"},
  {entry: "mendācium",
    genitive: "mendāciī",
    gender: "n.",
    meanings: "mendacity, deceptiveness"},
  {entry: "mēnsis",
    genitive: "mēnsis (pl. -ium)",
    gender: "m.",
    meanings: "month"},
  {entry: "merīdiēs",
    genitive: "merīdiēī",
    gender: "m.",
    meanings: "noon; south"},
  {entry: "mollītia",
    genitive: "mollītiae",
    gender: "f.",
    meanings: "softness, tenderness"},
  {entry: "mūnitiō",
    genitive: "mūnitiōnis",
    gender: "f.",
    meanings: "munition, the act of fortifying"},
  {entry: "-nitiō",
    genitive: "-nitiōnis",
    gender: "f.",
    meanings: "the act of recognizing or being aware"},
  {entry: "nōnae",
    genitive: "nōnārum",
    gender: "f.",
    meanings: "Nones, 5<sup>th</sup> or 7<sup>th</sup> of the month"},
  {entry: "nūmen",
    genitive: "nūminis",
    gender: "n.",
    meanings: "nod; natural spirit"},
  {entry: "ōmen",
    genitive: "ōminis",
    gender: "n.",
    meanings: "portent, sign of things to come"},
  {entry: "onus",
    genitive: "oneris",
    gender: "n.",
    meanings: "burden, responsbility"},
  {entry: "opus",
    genitive: "operis",
    gender: "n.",
    meanings: "work, accomplishment"},
  {entry: "petītiō",
    genitive: "petītiōnis",
    gender: "f.",
    meanings: "petition, lawsuit, the act of seeking"},
  {entry: "plūvia",
    genitive: "plūviae",
    gender: "f.",
    meanings: "rain, shower"},
  {entry: "positiō",
    genitive: "positiōnis",
    gender: "f.",
    meanings: "position, the act of placing"},
  {entry: "publicitās",
    genitive: "publicitātis",
    gender: "f.",
    meanings: "publicity"},
  {entry: "pulsiō",
    genitive: "pulsiōnis",
    gender: "f.",
    meanings: "the act of driving or pushing"},
  {entry: "quaestiō",
    genitive: "quaestiōnis",
    gender: "f.",
    meanings: "question, inquiry"},
  {entry: "rūs",
    genitive: "rūris",
    gender: "n.",
    meanings: "country, countryside"},
  {entry: "salūs",
    genitive: "salūtis",
    gender: "f.",
    meanings: "health"},
  {entry: "salūbritās",
    genitive: "salūbritātis",
    gender: "f.",
    meanings: "healthiness, healthfulness"},
  {entry: "sānitās",
    genitive: "sānitātis",
    gender: "f.",
    meanings: "health, soundness"},
  {entry: "sapor",
    genitive: "sapōris",
    gender: "m.",
    meanings: "flavor; wisdom, know-how"},
  {entry: "scelus",
    genitive: "sceleris",
    gender: "n.",
    meanings: "crime, sin, wickedness"},
  {entry: "scientia",
    genitive: "scientiae",
    gender: "f.",
    meanings: "knowledge; science"},
  {entry: "scrīptūra",
    genitive: "scrīptūrae",
    gender: "f.",
    meanings: "writing"},
  {entry: "servitium",
    genitive: "servitiī",
    gender: "n.",
    meanings: "slavery, servitude (the institution of)"},
  {entry: "servitūs",
    genitive: "servitūtis",
    gender: "f.",
    meanings: "servitude; the state of being a slave"},
  {entry: "-stitūtiō",
    genitive: "-stitutiōnis",
    gender: "f.",
    meanings: "the act of setting up or determining"},
  {entry: "structiō",
    genitive: "structiōnis",
    gender: "f.",
    meanings: "the act of building"},
  {entry: "structūra",
    genitive: "structūrae",
    gender: "f.",
    meanings: "building, structure; the result of building"},
  {entry: "trāditiō",
    genitive: "trāditiōnis",
    gender: "f.",
    meanings: "tradition; something handed down or over"},
  {entry: "tractiō",
    genitive: "tractiōnis",
    gender: "f.",
    meanings: "the act of pulling or dragging"},
  {entry: "vectiō",
    genitive: "vectiōnis",
    gender: "f.",
    meanings: "the act of conveying or transporting"},
  {entry: "ver",
    genitive: "veris",
    gender: "n.",
    meanings: "springtime"},
  {entry: "versiō",
    genitive: "versiōnis",
    gender: "f.",
    meanings: "version; the act of turning"}
]

let nounsLength = nounsReview4.length;

function displayNouns() {
  let j = 1;
  let html = `<ol style="1" start="${j}">`;
  let iteration = "";

  for (let i = 0; i < nounsLength; i++) {
    iteration += `<div id="noun-item-${j}" class="container-flex"><li id="li-${j}">`;
    iteration += `<div id="top-row-${j}" class="row">`
    iteration += `<span id="latin-span-${j}" style="width: 100%; margin-left: 20px"><strong>${nounsReview4[i].entry}, `;
    iteration += `${nounsReview4[i].genitive}</strong> `;
    iteration += `(${nounsReview4[i].gender}) `;
    iteration += ` — <em>${nounsReview4[i].meanings}</em></span>`;
    iteration += `</div></li><hr/>`;
    }
    j++;

  html += iteration;
  html += "</ol>";
  return html;
}
