const adjectivesReview3 = [
  {entry: "ācer/ācris/ācre",
  agreesWith: "hostem",
  adverbForm: "ācriter",
  meanings: "sharp, bitter, fierce",
  inflectedForm: "ācrem",
  superlativeForm: "ācerrimum"},
  {entry: "Aegyptius/-a/-um",
    agreesWith: "doctōrī",
    adverbForm: "",
    meanings: "Egyptian, or Egypt",
    inflectedForm: "Aegyptiō",
    superlativeForm: "Aegyptissimō"},
  {entry: "Āfricānus/-a/-um",
    agreesWith: "fontis",
    adverbForm: "",
    meanings: "African, or (northern) Africa",
    inflectedForm: "Āfricanī",
    superlativeForm: "Āfricanissimī"},
  {entry: "albus/-a/-um",
    agreesWith: "leōnibus",
    adverbForm: "",
    meanings: "white, off-white",
    inflectedForm: "albīs",
    superlativeForm: "albissimīs"},
  {entry: "altus/-a/-um",
    agreesWith: "regiōnis",
    adverbForm: "altē",
    meanings: "high, tall, deep",
    inflectedForm: "altae",
    superlativeForm: "altissimae"},
  {entry: "ambō/ambae/ambō",
    agreesWith: "virginēs (2)",
    adverbForm: "",
    meanings: "both (of two)",
    inflectedForm: "ambae/ambās",
    superlativeForm: ""},
  {entry: "Āsiānus/-a/-um",
    agreesWith: "volūmina",
    adverbForm: "",
    meanings: "Asian, of Asia Minor",
    inflectedForm: "Āsiāna",
    superlativeForm: "Āsiānissima"},
  {entry: "āter/ātra/ātrum",
    agreesWith: "stātuārum",
    adverbForm: "",
    meanings: "dull black",
    inflectedForm: "ātrārum",
    superlativeForm: "āterrimārum"},
  {entry: "audāx, audācis",
    agreesWith: "prīncipī",
    adverbForm: "audāciter",
    meanings: "bold, daring",
    inflectedForm: "audācī",
    superlativeForm: "audācissimō"},
  {entry: "aurantiācus/-a/-um",
    agreesWith: "abdōmen",
    adverbForm: "",
    meanings: "orange",
    inflectedForm: "aurantiācum",
    superlativeForm: "aurantiācissimum"},
  {entry: "brevis/-e",
    agreesWith: "tempore",
    adverbForm: "breviter",
    meanings: "short, brief",
    inflectedForm: "brevī",
    superlativeForm: "brevissimō"},
  {entry: "caerūleus/-a/-um",
    agreesWith: "flūmina",
    adverbForm: "",
    meanings: "sky blue",
    inflectedForm: "caerūlea",
    superlativeForm: "māximē caerūlea"},
  {entry: "calidus/-a/-um",
    agreesWith: "lūcum",
    adverbForm: "calidē",
    meanings: "hot",
    inflectedForm: "calidārum",
    superlativeForm: "calidissimārum"},
  {entry: "candidus/-a/-um",
    agreesWith: "togās",
    adverbForm: "candidē",
    meanings: "shining white, clear, bright, fair",
    inflectedForm: "candidās",
    superlativeForm: "candidissimās"},
  {entry: "captīvus/-a/-um",
    agreesWith: "cīvibus",
    adverbForm: "captīvē",
    meanings: "captive, taken prisoner",
    inflectedForm: "captīvīs",
    superlativeForm: "captīvissimīs"},
  {entry: "cārus/-a/-um",
    agreesWith: "ducis",
    adverbForm: "cārē",
    meanings: "dear, precious, expensive",
    inflectedForm: "cārī",
    superlativeForm: "cārissimī"},
  {entry: "celer/celeris/celere",
    agreesWith: "Mercūrī",
    adverbForm: "celeriter",
    meanings: "swift, fast",
    inflectedForm: "celer",
    superlativeForm: "celerrime"},
  {entry: "clārus/-a/-um",
    agreesWith: "gentibus",
    adverbForm: "clārē",
    meanings: "clear, bright, famous",
    inflectedForm: "clārīs",
    superlativeForm: "clārissimīs"},
  {entry: "Corsicus/-a/-um",
    agreesWith: "radīx",
    adverbForm: "",
    meanings: "Corsican, of Corsica",
    inflectedForm: "Corsica",
    superlativeForm: "Corsicissima"},
  {entry: "Crēticus/-a/-um",
    agreesWith: "ōrdinum",
    adverbForm: "",
    meanings: "Cretan, of Crete",
    inflectedForm: "Crēticōrum",
    superlativeForm: "Crēticissimōrum"},
  {entry: "Cypriānus/-a/-um",
    agreesWith: "avem",
    adverbForm: "",
    meanings: "Cypriot, of Cyprus",
    inflectedForm: "Cypriānam",
    superlativeForm: "Cypriānissimam"},
  {entry: "difficilis/-e",
    agreesWith: "latus",
    adverbForm: "difficile (difficiliter)",
    meanings: "difficult",
    inflectedForm: "difficile",
    superlativeForm: "difficillimum"},
  {entry: "dissimilis/-e",
    agreesWith: "pictūram",
    adverbForm: "dissimile (dissimiliter)",
    meanings: "unlike, dissimilar",
    inflectedForm: "dissimilem",
    superlativeForm: "dissimillimam"},
  {entry: "dīvēs, dīvitis",
    agreesWith: "politicōrum",
    adverbForm: "",
    meanings: "wealthy",
    inflectedForm: "dīvitum (dīvitium)",
    superlativeForm: "dīvitissimōrum"},
  {entry: "dulcis/-e",
    agreesWith: "olīvā",
    adverbForm: "dulciter",
    meanings: "sweet",
    inflectedForm: "dulcī",
    superlativeForm: "dulcissimā"},
  {entry: "duo/duae/duo",
    agreesWith: "honōrēs (2)",
    adverbForm: "",
    meanings: "two",
    inflectedForm: "duo, duōs",
    superlativeForm: ""},
  {entry: "Etruscus/-a/-um",
    agreesWith: "corpus",
    adverbForm: "",
    meanings: "Etruscan, of Etruria",
    inflectedForm: "Etruscum",
    superlativeForm: "Etruscissimum"},
  {entry: "facilis/-e",
    agreesWith: "carmen",
    adverbForm: "facile",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "falsus/-a/-um",
    agreesWith: "generī",
    adverbForm: "falsē",
    meanings: "false, deceptive",
    inflectedForm: "falsō",
    superlativeForm: "falsissimō"},
  {entry: "fēlīx, fēlīcis",
    agreesWith: "fēlem",
    adverbForm: "fēlīciter",
    meanings: "happy, lucky",
    inflectedForm: "fēlīcem",
    superlativeForm: "fēlīcissimam (or -um)"},
  {entry: "fīdēlis/-e",
    agreesWith: "alumnam",
    adverbForm: "fīdēliter",
    meanings: "faithful, trustworthy",
    inflectedForm: "fīdēlem",
    superlativeForm: "fīdēlissimam"},
  {entry: "flāvus/-a/-um",
    agreesWith: "canum",
    adverbForm: "",
    meanings: "yellow",
    inflectedForm: "flāvōrum",
    superlativeForm: "flāvissimōrum"},
  {entry: "fortis/-e",
    agreesWith: "senātrīcibus",
    adverbForm: "fortiter",
    meanings: "brave, strong",
    inflectedForm: "fortibus",
    superlativeForm: "fortissimīs"},
  {entry: "frigidus/-a/-um",
    agreesWith: "oceānō",
    adverbForm: "frigidē",
    meanings: "cold",
    inflectedForm: "frigidō",
    superlativeForm: "frigidissimō"},
  {entry: "fuscus/-a/-um",
    agreesWith: "asparagōs",
    adverbForm: "",
    meanings: "brown, dark brown, black",
    inflectedForm: "fuscōs",
    superlativeForm: "fuscissimōs"},
  {entry: "grāvis/-e",
    agreesWith: "vulnera",
    adverbForm: "grāviter",
    meanings: "heavy, serious",
    inflectedForm: "grāvia",
    superlativeForm: "grāvissima"},
  {entry: "grīseus/-a/-um",
    agreesWith: "Iōvī",
    adverbForm: "",
    meanings: "gray",
    inflectedForm: "grīseō",
    superlativeForm: "māximē grīseō"},
  {entry: "humānus/-a/-um",
    agreesWith: "memōriīs",
    adverbForm: "humānē",
    meanings: "human",
    inflectedForm: "humānīs",
    superlativeForm: "humānissimīs"},
  {entry: "humilis/-e",
    agreesWith: "urbium",
    adverbForm: "humiliter",
    meanings: "humble, lowly, low",
    inflectedForm: "humilium",
    superlativeForm: "humillimārum"},
  {entry: "īnfēlīx, īnfēlīcis",
    agreesWith: "lupe",
    adverbForm: "īnfēlīciter",
    meanings: "unhappy, unlucky",
    inflectedForm: "īnfēlīx",
    superlativeForm: "īnfēlīcissime"},
  {entry: "integer/-gra/-grum",
    agreesWith: "crūre",
    adverbForm: "integrē",
    meanings: "whole, unharmed",
    inflectedForm: "integrō",
    superlativeForm: "integerrimō"},
  {entry: "Iūdaeus/-a/-um",
    agreesWith: "nivis",
    adverbForm: "",
    meanings: "Judean, of Judea",
    inflectedForm: "Iudaeae",
    superlativeForm: "māximē Iudaeae"},
  {entry: "iuvenis/-e",
    agreesWith: "nepōtēs",
    adverbForm: "",
    meanings: "young",
    inflectedForm: "iuvenēs",
    superlativeForm: "iuvenissimī, iuvenissimōs"},
  {entry: "leōnīnus/-a/-um",
    agreesWith: "caput",
    adverbForm: "leōnīnē",
    meanings: "lionlike",
    inflectedForm: "leōnīnum",
    superlativeForm: "leōnīnissimum"},
  {entry: "levis/-e",
    agreesWith: "errōris",
    adverbForm: "leviter",
    meanings: "light, unserious",
    inflectedForm: "levis",
    superlativeForm: "levissimī"},
  {entry: "līber/-era/-erum",
    agreesWith: "pastōrum",
    adverbForm: "līberē",
    meanings: "free",
    inflectedForm: "līberōrum",
    superlativeForm: "līberissimōrum"},
  {entry: "Lūstiānus/-a/-um",
    agreesWith: "hominēs (at least 2)",
    adverbForm: "",
    meanings: "of Lusitania/Portugal",
    inflectedForm: "Lūsitānī, Lūsitānōs",
    superlativeForm: "Lūsitānissimī/-ōs"},
  {entry: "Macedōnicus/-a/-um",
    agreesWith: "noctium",
    adverbForm: "",
    meanings: "Macedonian, of Macedon",
    inflectedForm: "Macedōnicārum",
    superlativeForm: "Macedōnicārissimum"},
  {entry: "Maurus/-a/-um",
    agreesWith: "pāx",
    adverbForm: "",
    meanings: "Mauretanian, Moorish",
    inflectedForm: "Maura",
    superlativeForm: "Maurissima"},
  {entry: "niger/-gra/-grum",
    agreesWith: "nāve",
    adverbForm: "",
    meanings: "shining black",
    inflectedForm: "nigrā",
    superlativeForm: "nigerrimā"},
  {entry: "Numidiānus/-a/-um",
    agreesWith: "imperātōrī",
    adverbForm: "",
    meanings: "Numidian, of Numidia",
    inflectedForm: "Numidiānō",
    superlativeForm: "Numidiānissimō"},
  {entry: "obscūrus/-a/-um",
    agreesWith: "lentēs (2)",
    adverbForm: "obscūrē",
    meanings: "dark, shadowy, mysterious",
    inflectedForm: "obscūrae, obscūrās",
    superlativeForm: "obscūrissimae, -ās"},
  {entry: "omnis/-e",
    agreesWith: "Aegypitōs",
    adverbForm: "",
    meanings: "all, every",
    inflectedForm: "omnēs",
    superlativeForm: ""},
  {entry: "pār, paris",
    agreesWith: "cōnsulibus",
    adverbForm: "pariter",
    meanings: "equal",
    inflectedForm: "paribus",
    superlativeForm: "parissimīs"},
  {entry: "pauper, pauperis",
    agreesWith: "centuriōne",
    adverbForm: "",
    meanings: "poor, impoverished",
    inflectedForm: "paupere",
    superlativeForm: "pauperissimō"},
  {entry: "potēns, potentis",
    agreesWith: "vōcis",
    adverbForm: "potenter",
    meanings: "strong, powerful",
    inflectedForm: "potentis",
    superlativeForm: "potentissimae"},
  {entry: "prōfundus/-a/-um",
    agreesWith: "terror",
    adverbForm: "prōfundē",
    meanings: "deep, profound",
    inflectedForm: "prōfundus",
    superlativeForm: "prōfundissimus"},
  {entry: "purpureus/-a/-um",
    agreesWith: "corda",
    adverbForm: "",
    meanings: "purple",
    inflectedForm: "purpurea",
    superlativeForm: "māximē purpurea"},
  {entry: "pūrus/-a/-um",
    agreesWith: "ārtem",
    adverbForm: "pūrē",
    meanings: "pure, clean",
    inflectedForm: "pūram",
    superlativeForm: "pūrissimam"},
  {entry: "rōseus/-a/-um",
    agreesWith: "carne",
    adverbForm: "",
    meanings: "pink, rosy",
    inflectedForm: "rōseā",
    superlativeForm: "māximē rōseā"},
  {entry: "ruber/-bra/-brum",
    agreesWith: "ignis (at least 2)",
    adverbForm: "",
    meanings: "red",
    inflectedForm: "ruber, rubrī",
    superlativeForm: "ruberrimus, -e, -ī"},
  {entry: "sacer/-cra/-crum",
    agreesWith: "arbor",
    adverbForm: "sacrē",
    meanings: "sacred, hallowed",
    inflectedForm: "sacra",
    superlativeForm: "sacerrima"},
  {entry: "sānctus/-a/-um",
    agreesWith: "medicīnā",
    adverbForm: "sānctē",
    meanings: "holy, saintly",
    inflectedForm: "sānctā",
    superlativeForm: "sānctissimā"},
  {entry: "sapiēns, sapientis",
    agreesWith: "Minervae (2, s. only)",
    adverbForm: "sapienter",
    meanings: "wise, flavorful",
    inflectedForm: "sapitentis, sapientī",
    superlativeForm: "sapientissimae"},
  {entry: "senex, senis",
    agreesWith: "patri",
    adverbForm: "",
    meanings: "old, aged (usually referring to men)",
    inflectedForm: "senī",
    superlativeForm: "senissimō"},
  {entry: "similis/-e",
    agreesWith: "ōribus",
    adverbForm: "simile (similiter)",
    meanings: "like, similar (to)",
    inflectedForm: "similibus",
    superlativeForm: "simillimīs"},
  {entry: "sordidus/-a/-um",
    agreesWith: "dentēs (2)",
    adverbForm: "sordidē",
    meanings: "dirty",
    inflectedForm: "sordidae, sordidās",
    superlativeForm: "sordidissimae, -ās"},
  {entry: "Syrus/-a/-um",
    agreesWith: "nucum",
    adverbForm: "",
    meanings: "Syrian, of Syria",
    inflectedForm: "Syrārum",
    superlativeForm: "Syrissimārum"},
  {entry: "tepidus/-a/-um",
    agreesWith: "lacte",
    adverbForm: "tepidē",
    meanings: "warm, lukewarm",
    inflectedForm: "tepidā",
    superlativeForm: "tepidissimā"},
  {entry: "trēs/tria",
    agreesWith: "crucum",
    adverbForm: "",
    meanings: "three",
    inflectedForm: "trium",
    superlativeForm: ""},
  {entry: "trīstis/-e",
    agreesWith: "matrīmōniīs",
    adverbForm: "trīstiter",
    meanings: "sad, melancholy",
    inflectedForm: "trīstibus",
    superlativeForm: "trīstissimīs"},
  {entry: "turpis/-e",
    agreesWith: "Bacchō",
    adverbForm: "turpiter",
    meanings: "ugly, shameful, ",
    inflectedForm: "turpī",
    superlativeForm: "turpissimō"},
  {entry: "ūnus/-a/-um",
    agreesWith: "ōrātiōnis",
    adverbForm: "",
    meanings: "one",
    inflectedForm: "unīus",
    superlativeForm: ""},
  {entry: "vēlōx, vēlōcis",
    agreesWith: "legiōnibus",
    adverbForm: "vēlōciter",
    meanings: "fast, speedy",
    inflectedForm: "vēlōcibus",
    superlativeForm: "vēlōcissimīs"},
  {entry: "vērus/-a/-um",
    agreesWith: "uxōrum",
    adverbForm: "vērē",
    meanings: "true",
    inflectedForm: "vērārum",
    superlativeForm: "vērissimārum"},
  {entry: "vetus, veteris",
    agreesWith: "vehiculō (2)",
    adverbForm: "",
    meanings: "old, experienced",
    inflectedForm: "veterī, vetere",
    superlativeForm: "veterissimō/vetustissimō"},
  {entry: "viridis/-e",
    agreesWith: "tūnicārum",
    adverbForm: "",
    meanings: "green",
    inflectedForm: "viridium",
    superlativeForm: "viridissimārum"},
]

let adjectivesLength = adjectivesReview3.length;

function displayAdjectives() {
  let j = 1;
  let html = `<ol style="1" start="${j}">`;
  let iteration = "";

  for (let i = 0; i < adjectivesLength; i++) {
    iteration += `<div id="adjective-item-${j}" class="container-flex"><li id="li-${j}">`;
    iteration += `<div id="top-row-${j}" class="row">`
    iteration += `<span id="adjective-span-${j}" style="width: 30%; margin-left: 20px">${adjectivesReview3[i].entry}</span>`;
    iteration += `<span id="agrees-with-span-${j}" style="width: 30%">${adjectivesReview3[i].agreesWith}</span>`;
    iteration += `<span id="button-span-${j}"><button id="reveal${j}" class="reveal-answer btn btn-outline-dark" onclick="$('#answer-div-${j}').toggle();"><strong>Answer</strong></button></span></div>`;
    iteration += `<div id="answer-div-${j}" style="display: none">`
    iteration += `<span id="meaning-span${j}" style="margin-left: 10px">Meaning: <em>${adjectivesReview3[i].meanings}</em></span><br/>`;
    if (adjectivesReview3[i].adverbForm !== "") {
      iteration += `<span id="adverb-span-${j}" style="margin-left: 10px">Adverb: <strong>${adjectivesReview3[i].adverbForm}</strong></span><br/>`;
    }
    if (adjectivesReview3[i].superlativeForm !== "") {
      iteration += `<span id="inflected-span${j}" style="margin-left: 10px">Inflected Forms: <strong>${adjectivesReview3[i].inflectedForm}, ${adjectivesReview3[i].superlativeForm}</strong></span>`;
    } else {
      iteration += `<span id="inflected-span${j}" style="margin-left: 10px">Inflected Forms: <strong>${adjectivesReview3[i].inflectedForm}</strong></span></div>`;
    }
    iteration += `</div></li><hr/>`;
    }
    j++;

  html += iteration;
  html += "</ol>";
  return html;
}
