const adjectivesReview4 = [
  {entry: "aestīvus/-a/-um",
    comparative: "aestīvior",
    superlative: "aestivissimus",
    meanings: "summery, related to summer"},
  {entry: "aeternus/-a/-um",
    comparative: "aeternior",
    superlative: "aeternissimus",
    meanings: "eternal, perpetual"},
  {entry: "annuālis, -e",
    comparative: "---",
    superlative: "---",
    meanings: "annual, yearly, one year old"},
  {entry: "anterus/-a/-um",
    comparative: "anterior",
    superlative: "antīcus",
    meanings: "in front"},
  {entry: "citer/-tra/-trum",
    comparative: "citerior",
    superlative: "citimus",
    meanings: "on this side"},
  {entry: "clēmēns, -ntis",
    comparative: "clēmentior",
    superlative: "clēmentissimus",
    meanings: "merciful"},
  {entry: "commūnis/-e",
    comparative: "commūnior",
    superlative: "commūnissimus",
    meanings: "common"},
  {entry: "crīminālis/-e",
    comparative: "crīminālior",
    superlative: "crīminālissimus",
    meanings: "criminal, related to crime"},
  {entry: "crūdēlis/-e",
    comparative: "crūdēlior",
    superlative: "crūdēlissimus",
    meanings: "cruel"},
  {entry: "cupidus/-a/-um",
    comparative: "cupidior",
    superlative: "cupidissimus",
    meanings: "desirous"},
  {entry: "decorus/-a/-um",
    comparative: "decorior",
    superlative: "decorissimus",
    meanings: "right, proper, distinguished"},
  {entry: "dēmēns, -ntis",
    comparative: "dēmentior",
    superlative: "dēmentissimus",
    meanings: "out of one's mind"},
  {entry: "diārius/-a/-um",
    comparative: "---",
    superlative: "---",
    meanings: "daily, related to the day"},
  {entry: "dūrus/-a/-um",
    comparative: "dūrior",
    superlative: "dūrissimus",
    meanings: "hard, rigid"},
  {entry: "exter/-tera/-terum",
    comparative: "exterior",
    superlative: "extrēmus",
    meanings: "outer"},
  {entry: "fugitīvus/-a/-um",
    comparative: "---",
    superlative: "---",
    meanings: "fugitive, in flight"},
  {entry: "grāmineus/-a/-um",
    comparative: "māgis grāmineus",
    superlative: "māximē grāmineus",
    meanings: "grassy, herbaceous"},
  {entry: "hibernus/-a/-um",
    comparative: "hibernior",
    superlative: "hibernissimus",
    meanings: "wintry, related to winter"},
  {entry: "hostīlis/-e",
    comparative: "hostīlior",
    superlative: "hostīlissimus",
    meanings: "hostile, related to an enemy"},
  {entry: "idōneus/-a/-um",
    comparative: "māgis idōneus",
    superlative: "māximē idōneus",
    meanings: "summery, related to summer"},
  {entry: "aestīvus/-a/-um",
    comparative: "aestīvior",
    superlative: "aestivissimus",
    meanings: "suitable, proper"},
  {entry: "īnferus/-a/-um",
    comparative: "īnferior",
    superlative: "īmus",
    meanings: "low"},
  {entry: "īngēns, -ntis",
    comparative: "īngentior",
    superlative: "īngentissimus",
    meanings: "huge"},
  {entry: "intrā",
    comparative: "interior",
    superlative: "intimus",
    meanings: "within, inner, innermost"},
  {entry: "iūstus/-a/-um",
    comparative: "iūstior",
    superlative: "iūstissimus",
    meanings: "just, fair, right"},
  {entry: "legibilis/-e",
    comparative: "legibilior",
    superlative: "legibilissimus",
    meanings: "readable, legible"},
  {entry: "līmināris/-e",
    comparative: "līminārior",
    superlative: "līminārissimus",
    meanings: "liminal, on the threshold"},
  {entry: "lītorālis/-e",
    comparative: "lītorālior",
    superlative: "lītorālissimus",
    meanings: "related to the seashore"},
  {entry: "medius/-a/-um",
    comparative: "---",
    superlative: "---",
    meanings: "middle, in the middle (of)"},
  {entry: "mendāx, -cis",
    comparative: "mendācior",
    superlative: "mendacissimus",
    meanings: "deceptive, mendacious, prone to lying"},
  {entry: "mēnstruus/-a/-um",
    comparative: "---",
    superlative: "---",
    meanings: "monthly, related to a month"},
  {entry: "mollis/-e",
    comparative: "mollior",
    superlative: "mollissimus",
    meanings: "soft, tender"},
  {entry: "ōminōsus/-a/-um",
    comparative: "ōminōsior",
    superlative: "ōminōsissimus",
    meanings: "ominous, portentous, foreboding"},
  {entry: "positīvus/-a/-um",
    comparative: "positīvior",
    superlative: "positīvissimus",
    meanings: "positive"},
  {entry: "populāris/-e",
    comparative: "populārior",
    superlative: "populārissimus",
    meanings: "popular, of or among the people"},
  {entry: "posterus/-a/-um",
    comparative: "posterior",
    superlative: "postrēmus",
    meanings: "in back, behind"},
  {entry: "prae",
    comparative: "prior",
    superlative: "prīmus",
    meanings: "early, before"},
  {entry: "prope",
    comparative: "propior",
    superlative: "prōximus",
    meanings: "near, next"},
  {entry: "publicus/-a/-um",
    comparative: "publicior",
    superlative: "publicissimus",
    meanings: "public, of the people"},
  {entry: "rūrālis/-e",
    comparative: "rūrālior",
    superlative: "rūrālissimus",
    meanings: "rural, rustic, related to the countryside"},
  {entry: "rūsticus/-a/-um",
    comparative: "rūsticior",
    superlative: "rūsticissimus",
    meanings: "country-style, rustic"},
  {entry: "salūber/-bra/-brum",
    comparative: "salūbrior",
    superlative: "salūberrimus",
    meanings: "healthy, healthful"},
  {entry: "sānus/-a/-um",
    comparative: "sānior",
    superlative: "sānissimus",
    meanings: "healthy, sound, sane"},
  {entry: "sapiēns, -ntis",
    comparative: "sapientior",
    superlative: "sapientissimus",
    meanings: "flavorful; wise, knowledgeable"},
  {entry: "scelestus/-a/-um",
    comparative: "scelestior",
    superlative: "scelestissimus",
    meanings: "wicked, criminal, sinful"},
  {entry: "superus/-a/-um",
    comparative: "superior",
    superlative: "suprēmus/summus",
    meanings: "high, above"},
  {entry: "ulter/-era/-erum",
    comparative: "ulterior",
    superlative: "ultimus",
    meanings: "summery, related to summer"},
  {entry: "vernālis/-e",
    comparative: "vernālior",
    superlative: "vernālissimus",
    meanings: "springlike, related to springtime"},
]

let adjectivesLength = adjectivesReview4.length;

function displayadjectives() {
  let j = 1;
  let html = `<ol style="1" start="${j}">`;
  let iteration = "";

  for (let i = 0; i < adjectivesLength; i++) {
    iteration += `<div id="adjective-item-${j}" class="container-flex"><li id="li-${j}">`;
    iteration += `<div id="top-row-${j}" class="row">`
    iteration += `<span id="latin-span-${j}" style="width: 100%; margin-left: 20px"><strong>${adjectivesReview4[i].entry} `;
    if (adjectivesReview4[i].comparative != "---") {
      iteration += `(${adjectivesReview4[i].comparative}, `;
      iteration += `${adjectivesReview4[i].superlative}) `;
    }
    iteration += `</strong> — <em>${adjectivesReview4[i].meanings}</em></span>`;
    iteration += `</div></li><hr/>`;
    }
    j++;

  html += iteration;
  html += "</ol>";
  return html;
}
