const adjectivesReview3 = [
  {entry: "ācer/ācris/ācre",
  adverbForm: "ācriter",
  meanings: "sharp, bitter, fierce",
  inflectedForm: "ācrem",
  superlativeForm: "ācerrimum"},
  {entry: "Aegyptius/-a/-um",
    adverbForm: "",
    meanings: "Egyptian, or Egypt",
    inflectedForm: "Aegyptiō",
    superlativeForm: "Aegyptissimō"},
  {entry: "Āfricānus/-a/-um",
    adverbForm: "",
    meanings: "African, or (northern) Africa",
    inflectedForm: "Āfricanī",
    superlativeForm: "Āfricanissimī"},
  {entry: "albus/-a/-um",
    adverbForm: "",
    meanings: "white, off-white",
    inflectedForm: "albīs",
    superlativeForm: "albissimīs"},
  {entry: "altus/-a/-um",
    adverbForm: "altē",
    meanings: "high, tall, deep",
    inflectedForm: "altae",
    superlativeForm: "altissimae"},
  {entry: "ambō/ambae/ambō",
    adverbForm: "",
    meanings: "both (of two)",
    inflectedForm: "ambae/ambās",
    superlativeForm: ""},
  {entry: "Āsiānus/-a/-um",
    adverbForm: "",
    meanings: "Asian, of Asia Minor",
    inflectedForm: "Āsiāna",
    superlativeForm: "Āsiānissima"},
  {entry: "āter/ātra/ātrum",
    adverbForm: "",
    meanings: "dull black",
    inflectedForm: "ātrārum",
    superlativeForm: "āterrimārum"},
  {entry: "audāx, audācis",
    adverbForm: "audāciter",
    meanings: "bold, daring",
    inflectedForm: "audācī",
    superlativeForm: "audācissimō"},
  {entry: "aurantiācus/-a/-um",
    adverbForm: "",
    meanings: "orange",
    inflectedForm: "aurantiācum",
    superlativeForm: "aurantiācissimum"},
  {entry: "brevis/-e",
    adverbForm: "breviter",
    meanings: "short, brief",
    inflectedForm: "brevī",
    superlativeForm: "brevissimō"},
  {entry: "caerūleus/-a/-um",
    adverbForm: "",
    meanings: "sky blue",
    inflectedForm: "caerūlea",
    superlativeForm: "māximē caerūlea"},
  {entry: "calidus/-a/-um",
    adverbForm: "calidē",
    meanings: "hot",
    inflectedForm: "calidārum",
    superlativeForm: "calidissimārum"},
  {entry: "candidus/-a/-um",
    adverbForm: "candidē",
    meanings: "shining white, clear, bright, fair",
    inflectedForm: "candidās",
    superlativeForm: "candidissimās"},
  {entry: "captīvus/-a/-um",
    adverbForm: "captīvē",
    meanings: "captive, taken prisoner",
    inflectedForm: "captīvīs",
    superlativeForm: "captīvissimīs"},
  {entry: "cārus/-a/-um",
    adverbForm: "cārē",
    meanings: "dear, precious, expensive",
    inflectedForm: "cārī",
    superlativeForm: "cārissimī"},
  {entry: "celer/celeris/celere",
    adverbForm: "celeriter",
    meanings: "swift, fast",
    inflectedForm: "celer",
    superlativeForm: "celerrime"},
  {entry: "clārus/-a/-um",
    adverbForm: "clārē",
    meanings: "clear, bright, famous",
    inflectedForm: "clārīs",
    superlativeForm: "clārissimīs"},
  {entry: "Corsicus/-a/-um",
    adverbForm: "",
    meanings: "Corsican, of Corsica",
    inflectedForm: "Corsica",
    superlativeForm: "Corsicissima"},
  {entry: "Crēticus/-a/-um",
    adverbForm: "",
    meanings: "Cretan, of Crete",
    inflectedForm: "Crēticōrum",
    superlativeForm: "Crēticissimōrum"},
  {entry: "Cypriānus/-a/-um",
    adverbForm: "",
    meanings: "Cypriot, of Cyprus",
    inflectedForm: "Cypriānam",
    superlativeForm: "Cypriānissimam"},
  {entry: "difficilis/-e",
    adverbForm: "difficile (difficiliter)",
    meanings: "difficult",
    inflectedForm: "difficile",
    superlativeForm: "difficillimum"},
  {entry: "dissimilis/-e",
    adverbForm: "dissimile (dissimiliter)",
    meanings: "unlike, dissimilar",
    inflectedForm: "dissimilem",
    superlativeForm: "dissimillimam"},
  {entry: "dīvēs, dīvitis",
    adverbForm: "",
    meanings: "wealthy",
    inflectedForm: "dīvitum (dīvitium)",
    superlativeForm: "dīvitissimōrum"},
  {entry: "dulcis/-e",
    adverbForm: "dulciter",
    meanings: "sweet",
    inflectedForm: "dulcī",
    superlativeForm: "dulcissimā"},
  {entry: "duo/duae/duo",
    adverbForm: "",
    meanings: "two",
    inflectedForm: "duo, duōs",
    superlativeForm: ""},
  {entry: "Etruscus/-a/-um",
    adverbForm: "",
    meanings: "Etruscan, of Etruria",
    inflectedForm: "Etruscum",
    superlativeForm: "Etruscissimum"},
  {entry: "facilis/-e",
    adverbForm: "facile",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "falsus/-a/-um",
    adverbForm: "falsē",
    meanings: "false, deceptive",
    inflectedForm: "falsō",
    superlativeForm: "falsissimō"},
  {entry: "fēlīx, fēlīcis",
    adverbForm: "fēlīciter",
    meanings: "happy, lucky",
    inflectedForm: "fēlīcem",
    superlativeForm: "fēlīcissimam (or -um)"},
  {entry: "fīdēlis/-e",
    adverbForm: "fīdēliter",
    meanings: "faithful, trustworthy",
    inflectedForm: "fīdēlem",
    superlativeForm: "fīdēlissimam"},
  {entry: "flāvus/-a/-um",
    adverbForm: "",
    meanings: "yellow",
    inflectedForm: "flāvōrum",
    superlativeForm: "flāvissimōrum"},
  {entry: "fortis/-e",
    adverbForm: "fortiter",
    meanings: "brave, strong",
    inflectedForm: "fortibus",
    superlativeForm: "fortissimīs"},
  {entry: "frigidus/-a/-um",
    adverbForm: "frigidē",
    meanings: "cold",
    inflectedForm: "frigidō",
    superlativeForm: "frigidissimō"},
  {entry: "fuscus/-a/-um",
    adverbForm: "",
    meanings: "brown, dark brown, black",
    inflectedForm: "fuscōs",
    superlativeForm: "fuscissimōs"},
  {entry: "grāvis/-e",
    adverbForm: "grāviter",
    meanings: "heavy, serious",
    inflectedForm: "grāvia",
    superlativeForm: "grāvissima"},
  {entry: "grīseus/-a/-um",
    adverbForm: "",
    meanings: "gray",
    inflectedForm: "grīseō",
    superlativeForm: "māximē grīseō"},
  {entry: "humānus/-a/-um",
    adverbForm: "humānē",
    meanings: "human",
    inflectedForm: "humānīs",
    superlativeForm: "humānissimīs"},
  {entry: "humilis/-e",
    adverbForm: "humiliter",
    meanings: "humble, lowly, low",
    inflectedForm: "humilium",
    superlativeForm: "humillimārum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},
  {entry: "ācer/ācris/ācre",
    adverbForm: "ācriter",
    meanings: "sharp, bitter, fierce",
    inflectedForm: "ācrem",
    superlativeForm: "ācerrimum"},

]

const adjectivesLatin = ["amīcus/-a/-um", "angustus/-a/-um", "antīquus/-a/-um", "aquilīnus/-a/-um", "asinīnus/-a/-um",
  "benīgnus/-a/-um", "bovīnus/-a/-um", "Britānnus/-a/-um", "cervīnus/-a/-um", "Dācus/-a/-um", "equīnus/-a/-um",
  "Eurōpaeus/-a/-um", "Gallus/-a/-um", "Germānus/-a/-um", "Graecus/-a/-um", "Helvētius/-a/-um", "Hispānus/-a/-um",
  "Illyrius/-a/-um", "inimīcus/-a/-um", "lātus/-a/-um", "longinquus/-a/-um",
  "longus/-a/-um", "novus/-a/-um", "porcīnus/-a/-um", "propinquus/-a/-um", "pulcher/-chra/-chrum",
  "Sardus/-a/-um", "Siculus/-a/-um", "suus/-a/-um", "taurīnus/-a/-um", "Thrāx", "vaccīnus/-a/-um", "validus/-a/-um"];

const adjectivesAgreeWith = ["imperium", "gladiō", "amīcitiam", "puer (2)", "nautam", "nūntī (2)", "incolārum",
  "populōs", "fīliās", "auxilia", "deīs", "patriae", "silvārum", "portīs", "aquilā", "lectōrum", "rēgīna",
  "responsīs", "scūtum", "porcō", "locī", "sagittīs", "servābus", "magistrōs", "pugnae", "asinōs", "decentiā",
  "beneficī", "angustiārum", "scribae (2)", "pecūnia", "dōna", "cerve"]

const adjectivesAnswers = [
  "<em>friendly</em>—<strong>amīcum</strong>",
  "<em>narrow</em>—<strong>angustō</strong>",
  "<em>ancient, of old</em>—<strong>antīquam</strong>",
  "<em>eagle-like</em>—<strong>aquilīnus, aquilīne</strong>",
  "<em>donkey-like</em>—<strong>asinīnum/-am</strong>",
  "<em>kindly</em>—<strong>benīgnī, benīgne</strong>",
  "<em>cattle-like</em>—<strong>bovīnōrum/-ārum</strong>",
  "<em>British, Briton</em>—<strong>Britānnōs</strong>",
  "<em>deer-like</em>—<strong>cervīnās</strong>",
  "<em>Dacian</em>—<strong>Dāca</strong>",
  "<em>horse-like</em>—<strong>equīnīs</strong>",
  "<em>European</em>—<strong>Eurōpaeae</strong>",
  "<em>Gallic, Celtic</em>—<strong>Gallārum</strong>",
  "<em>German, Germanic</em>—<strong>Germānīs</strong>",
  "<em>Greek</em>—<strong>Graecā</strong>",
  "<em>Helvetia, Swiss</em>—<strong>Helvētiōrum</strong>",
  "<em>Spanish</em>—<strong>Hispāna</strong>",
  "<em>Illyrian</em>—<strong>Illyriīs</strong>",
  "<em>unfriendly</em>—<strong>inimīcum</strong>",
  "<em>wide, broad</em>—<strong>lātō</strong>",
  "<em>far away</em>—<strong>longinquī</strong>",
  "<em>long</em>—<strong>longīs</strong>",
  "<em>new, strange</em>—<strong>novīs</strong>",
  "<em>pig-like</em>—<strong>porcīnōs</strong>",
  "<em>nearby, close (to)</em>—<strong>propinquae</strong>",
  "<em>beautiful, handsome</em>—<strong>pulchrōs</strong>",
  "<em>Sardinian</em>—<strong>Sardā</strong>",
  "<em>Sicilian</em>—<strong>Sicule</strong>",
  "<em>his/her/its/their own</em>—<strong>suārum</strong>",
  "<em>bull-like</em>—<strong>taurīnī/-ae, taurīnō/-ae</strong>",
  "<em>Thracian</em>—<strong>Thrāx</strong>",
  "<em>cow-like</em>—<strong>vaccīna</strong>",
  "<em>strong, healthy</em>—<strong>valide</strong>",
];

let adjectivesLength = adjectivesLatin.length;

function displayAdjectives() {
  let html = `<ol style="1" start="1">`;
  let iteration = "";
  let j = 1;
  for (let i = 0; i < adjectivesLength; i++) {
    iteration += `<li><div class="row" id="li-${j}" style="width: 100%; height: 50px">`;
    iteration += `<span id="adjective-span-${j}" class="col-3">${adjectivesLatin[i]}</span>`;
    iteration += `<span id="button-span-${j}" class="col-1"><button id="reveal${j}" class="reveal-vocab btn btn-outline-dark">--></button></span>`;
    iteration += `<span id="agrees-with-${j}" class="col-2" style="margin-left: 10px">${adjectivesAgreeWith[i]}</span>`;
    iteration += `<span id="vocab${j}" class="vocab-span col-4">${adjectivesAnswers[i]}</span></li>`;
    j++;
  }
  html += iteration;
  html += "</ol>";
  return html;
}
